### ISSUE TITLE
404 error: Invalid identifier provided

### ISSUE THREAD

**Issue by adarshkhatri** [laminas-api-tools/statuslib-example#4]
### Bug Report
When I do `domain.com/status/1` it throws this error:

> "title": "Not Found",
>     "status": 404,
>     "detail": "Invalid identifier provided"

But when doing `domain.com/status/3b7e0cb2-0565-4645-8512-ed9b86c85bd3` gives the right result. 

**What am I missing?**

**Comment by weierophinney** [comment]
You're not missing anything.

The identifier used in the URL should be the UUID generated for the entity, which is what is stored in the `id` field of the sample `status` table we provide. `1` is an unknown (and, in this case, invalid) identifier, while the UUID you provide in the second example is known and correct.

In other words, you're observing exactly the intended behavior; it's not what _you_ expected based on assumptions you had coming in, but it's what the statuslib intends.

**Comment by adarshkhatri** [comment]
I see. I also thought so. But your sample data does have `1`. https://github.com/laminas-api-tools/statuslib-example/blob/master/data/sample-data/db-sqlite-insert.sql#L1

**Comment by weierophinney** [comment]
Please ignore the data sets provided.

This library was originally developed as part of an Apigility workshop. We included the integer IDs in the data sets _to demonstrate functionality in the library_.

If you look at these lines in the source code for the provided mappers:

- https://github.com/laminas-api-tools/statuslib-example/blob/master/src/TableGatewayMapper.php#L75
- https://github.com/laminas-api-tools/statuslib-example/blob/master/src/ArrayMapper.php#L101

you will see that when you attempt to fetch an item, if the identifier is not a UUID, we _throw an exception_, and, moreover, it's a 404. This was to demonstrate how problem details could be generated from exceptions.

The behavior you observe _is correct_.
